# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Gregor\Documents\GitHub\video-quality-metrics\vqm_overview_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFrame


class Ui_FrameOverviewMode(QFrame):
    def setupUi(self):
        self.setObjectName("FrameOverviewMode")
        self.resize(492, 83)
        
        self.gridLayout_2 = QtWidgets.QGridLayout(self)
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        self.checkBoxEnableOverviewMode = QtWidgets.QCheckBox(self)
        self.checkBoxEnableOverviewMode.setObjectName("checkBoxEnableOverviewMode")
        
        self.gridLayout_2.addWidget(self.checkBoxEnableOverviewMode, 0, 0, 1, 1)
        self.widgetBorder = QtWidgets.QWidget(self)
        self.widgetBorder.setEnabled(True)
        self.widgetBorder.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widgetBorder.setObjectName("widgetBorder")
        self.gridLayout = QtWidgets.QGridLayout(self.widgetBorder)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.widgetBorder)
        self.widget.setEnabled(True)
        self.widget.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.widget.setObjectName("widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelInterval = QtWidgets.QLabel(self.widget)
        self.labelInterval.setObjectName("labelInterval")
        self.gridLayout_3.addWidget(self.labelInterval, 0, 0, 1, 1)
        self.lineEditInterval = QtWidgets.QLineEdit(self.widget)
        self.lineEditInterval.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEditInterval.setObjectName("lineEditInterval")
        self.gridLayout_3.addWidget(self.lineEditInterval, 0, 1, 1, 1)
        self.labelClipLength = QtWidgets.QLabel(self.widget)
        self.labelClipLength.setObjectName("labelClipLength")
        self.gridLayout_3.addWidget(self.labelClipLength, 0, 2, 1, 1)
        self.lineEditClipLength = QtWidgets.QLineEdit(self.widget)
        self.lineEditClipLength.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEditClipLength.setObjectName("lineEditClipLength")
        self.gridLayout_3.addWidget(self.lineEditClipLength, 0, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widgetBorder, 1, 0, 1, 1)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, FrameOverviewMode):
        _translate = QtCore.QCoreApplication.translate
        self.checkBoxEnableOverviewMode.setText(_translate("FrameOverviewMode", "Enable overview mode (optional)"))
        self.labelInterval.setText(_translate("FrameOverviewMode", "Interval (seconds)"))
        self.lineEditInterval.setPlaceholderText(_translate("FrameOverviewMode", "60"))
        self.labelClipLength.setText(_translate("FrameOverviewMode", "Clip Length (seconds)"))
        self.lineEditClipLength.setPlaceholderText(_translate("FrameOverviewMode", "2"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     FrameOverviewMode = QtWidgets.QFrame()
#     ui = Ui_FrameOverviewMode()
#     ui.setupUi(FrameOverviewMode)
#     FrameOverviewMode.show()
#     sys.exit(app.exec_())
